### ISSUE TITLE
PandaPower and Matpower give different results for SimBench grids

### ISSUE THREAD

**Issue by TobiasRitschel** [e2nIEE/simbench#13]
I am using PandaPower to convert SimBench grids to the Matpower format, and I am trying to verify that I am doing it correctly.

Therefore, I compare the results obtained using PandaPower to those obtained with Matpower, but there are discrepancies between the two.

I have attached the Python and Matlab scripts that I use (the Matpower path in line 15 must be changed).

If I use the same scripts for the PandaPower example networks, I get absolute errors on the order of 1e-10. I have tested this for the smallest grids up to case1354pegase (https://pandapower.readthedocs.io/en/v2.6.0/networks.html). To be specific, I edit line 22 in the Python script and comment out lines 25, 28, and 38.

Looking at the branch results for 1-LV-rural1--2-no_sw, my impression is that when using PandaPower, more power is lost in the transformer connecting the external grid to the rest of the buses.

Perhaps there is some aspect of the PandaPower/SimBench datastructures that I'm missing?
[mwe_2021_04_26.zip](https://github.com/e2nIEE/simbench/files/6378061/mwe_2021_04_26.zip)

**Comment by DavidEnergie** [comment]
Without having looked at your code, I guess it is because Matpower doesn't model transformer iron losses.

To test, set the PPC iron losses to zero and you should get the same results.

**Comment by TobiasRitschel** [comment]
Thank you for the fast answer. I have verified that setting the transformer iron losses using

net["trafo"]["pfe_kw"] = 0

in the Python script leads to very small absolute errors. I have tested for the 6 low voltage (LV) SimBench grids.

Therefore, I mark the issue as closed.
