### ISSUE TITLE
Repeating problems within various operations

### ISSUE THREAD

**Issue by skortmann** [e2nIEE/simbench#14]
C:\APPS\Anaconda3\envs\pandapower_env\lib\site-packages\simbench\converter\csv_pp_converter.py:390: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  idx_bus = data["Measurement"].index.difference(idx_line | idx_trafo).astype(int)
C:\APPS\Anaconda3\envs\pandapower_env\lib\site-packages\simbench\converter\csv_pp_converter.py:468: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  missing = csv_data["Line"].index.difference(idx_lines | idx_dclines)
C:\APPS\Anaconda3\envs\pandapower_env\lib\site-packages\simbench\converter\csv_pp_converter.py:472: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  if len(idx_lines & idx_dclines):
C:\APPS\Anaconda3\envs\pandapower_env\lib\site-packages\simbench\converter\csv_pp_converter.py:829: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  columns=input_data[corr_str].columns | Type_col_except_std_type)

(pandapower_env) C:\>conda list
# packages in environment at C:\APPS\Anaconda3\envs\pandapower_env:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py39h2bbff1b_1
asttokens                 2.0.5                    pypi_0    pypi
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     21.2.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
bleach                    3.3.0              pyhd3eb1b0_0
ca-certificates           2021.5.25            haa95532_1
certifi                   2021.5.30        py39haa95532_0
cffi                      1.14.5           py39hcd4344a_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              3.4.7                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.3              py39haa95532_0
et-xmlfile                1.1.0                    pypi_0    pypi
executing                 0.6.0                    pypi_0    pypi
geographiclib             1.50                     pypi_0    pypi
geopy                     2.1.0                    pypi_0    pypi
git                       2.23.0               h6bb4b03_0
icecream                  2.1.0                    pypi_0    pypi
importlib-metadata        3.10.0           py39haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 5.3.4            py39h7b7c402_0
ipython                   7.22.0           py39hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.17.2           py39haa95532_1
jinja2                    3.0.0              pyhd3eb1b0_0
jsonschema                3.2.0                      py_2
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py39haa95532_0
jupyterlab_pygments       0.1.2                      py_0
kiwisolver                1.3.1                    pypi_0    pypi
libsodium                 1.0.18               h62dcd97_0
llvmlite                  0.36.0                   pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                2.0.1            py39h2bbff1b_0
matplotlib                3.4.2                    pypi_0    pypi
mistune                   0.8.4           py39h2bbff1b_1000
msys2-conda-epoch         20160418                      1
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7            py39haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
networkx                  2.5.1                    pypi_0    pypi
notebook                  6.4.0            py39haa95532_0
numba                     0.53.1                   pypi_0    pypi
numpy                     1.20.3                   pypi_0    pypi
openpyxl                  3.0.7                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
packaging                 20.9               pyhd3eb1b0_0
pandapower                2.6.0                    pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pandoc                    2.12                 haa95532_0
pandocfilters             1.4.3            py39haa95532_1
parso                     0.7.0                      py_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.2           py39haa95532_0
plotly                    4.14.3                   pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
prometheus_client         0.11.0             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyh06a4308_0
py                        1.10.0                   pypi_0    pypi
pycparser                 2.20                       py_2
pygments                  2.9.0              pyhd3eb1b0_0
pyparsing                 2.4.7              pyhd3eb1b0_0
pyrsistent                0.17.3           py39h2bbff1b_0
pytest                    6.2.4                    pypi_0    pypi
python                    3.9.5                h6244533_3
python-dateutil           2.8.1              pyhd3eb1b0_0
python-igraph             0.9.6                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywin32                   228              py39he774522_0
pywinpty                  0.5.7            py39haa95532_0
pyzmq                     20.0.0           py39hd77b12b_1
retrying                  1.3.3                    pypi_0    pypi
scipy                     1.6.0                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py39haa95532_0
simbench                  1.2.0                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.35.4               h2bbff1b_0
terminado                 0.9.4            py39haa95532_0
testpath                  0.4.4              pyhd3eb1b0_0
texttable                 1.6.3                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tornado                   6.1              py39h2bbff1b_0
traitlets                 5.0.5              pyhd3eb1b0_0
tzdata                    2020f                h52ac0ba_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
webencodings              0.5.1            py39haa95532_1
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py39h2bbff1b_0
winpty                    0.4.3                         4
xlrd                      2.0.1                    pypi_0    pypi
xlsxwriter                1.4.3                    pypi_0    pypi
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.1              pyhd3eb1b0_0

**Comment by SteffenMeinecke** [comment]
The FutureWarning you mentioned are not yet a problem to this repository. However, with the commit https://github.com/e2nIEE/simbench/commit/646cc06607b997734f9180eaade1930ae5806b69 this issue should be solved (develop branch). It would be helpful If you checkout the development branch of simbench and check that with your installation.
