### ISSUE TITLE
mv_add1 data is incomplete in '1-HVMV-mixed-all-1-sw'

### ISSUE THREAD

**Issue by vogt31337** [e2nIEE/simbench#15]
Hi,

I'm trying to use simbench, especially the model '1-HVMV-mixed-all-1-sw'. And I just found out, that 'mv_add1' is missing three data columns. In the model there are 46 generators of type 'mv_add1', but there are only 43 profiles available.

 @SteffenMeinecke 

BR

**Comment by SteffenMeinecke** [comment]
hi @vogt31337 ,
thanks for your comment. Unfortunately, i can't reproduce the problem. Please test the following code snippet:

```
import simbench as sb
code = '1-HVMV-mixed-all-1-sw'
net = sb.get_simbench_net(code)
print("number of available renewables profiles: %i" % len(
    net.profiles["renewables"].columns.difference("time")))
print("number of used/needed renewables profiles: %i" % len(set(net.sgen.profile))
if "mv_add1" in net.profiles["renewables"].columns:
    print("profile 'mv_add1' is available.")
```
