### ISSUE TITLE
Description of grids in dataset

### ISSUE THREAD

**Issue by eddie-atkinson** [e2nIEE/simbench#17]
Hi folks,

First of all thank you for publishing such a useful dataset. Realistic load profiles combined with the topology of the network on which they are situated is sorely needed. 

For my own personal understanding of these datasets I think it would be nice to include some single line diagrams, and potentially a little more context as to what the various networks are, and how they are structured. 

I am aware you can use `simple_plot` with pandapower, but I feel that doesn't provide as much information as diagrams and descriptions.

I am specifically interested in the LV grids

**Comment by SteffenMeinecke** [comment]
Hi @eddie-atkinson,
there are some plots and descriptions at https://www.mdpi.com/1996-1073/13/12/3290 and https://simbench.readthedocs.io/en/stable/networks.html. All residual plots and discriptions can be found at chapter 4 of the SimBench documentation at https://simbench.de/en/download/publications/.

**Comment by eddie-atkinson** [comment]
Thanks @SteffenMeinecke  :)
