### ISSUE TITLE
Weather data for renewables generation

### ISSUE THREAD

**Issue by e-dism** [e2nIEE/simbench#19]
First, I want to thank the whole team for their work. Simbench is a very useful dataset.

I want to combine the simbench dataset with the weather data for testing an analysis method. 
For generating additional environmental condition profiles, I used weather stations near the geographic coordinates of the busses the wind power plants are connected. According to the simbench documentation, I tried to use weather data from DWD for 2011, 2012, and 2017. This way seems to fail because the wind profiles are very low correlated with the wind speed data from DWD. 

Is there a way to get more detailed information on which data (year) is used to model renewables generation? 

I tried it for the 1-HV-mixed grid but also need it for the EHV grid.

**Comment by dzanansarajlic** [comment]
Thank you for using SimBench and for your feedback.
Regarding your question, for wind parks DWD weather data for 2011 was used, and for the PV time series we used DWD data for 2012.
The weather data was used as the input for the agent-based simulation environment [SIMONA ](https://github.com/ie3-institute/simona) that generates the time series for renewables.
The [documentation](https://simona.readthedocs.io/en/latest/) of SIMONA and its wind energy converter model might also be helpful.
