### ISSUE TITLE
Question: Integrating new load profiles

### ISSUE THREAD

**Issue by buddih09** [e2nIEE/simbench#25]
Thank you for the very useful library. 
May I ask you what would be the best way if I want to integrate new load profiles to use with an existing benchmark grid in Simbench?

Thank you!

**Comment by SteffenMeinecke** [comment]
@buddih09 Since you post in this Repo, I guess you are using SimBench with pandapower. Then simply add new profiles to `net.profiles` and assign elements to the additional profile within the element tables `net.load`, `net.sgen`, ...
