### ISSUE TITLE
pandas deprecated .append -> warning for loading grids

### ISSUE THREAD

**Issue by okraft97** [e2nIEE/simbench#27]
pandas has deprecated .append for DataFrames since Version 1.4.0, meaning that loading a simbench grid now comes with the warning at "buses_at_sw = net.switch.bus.append(net.switch.element.loc[net.switch.et == "b"])" in extract_simbench_grid_from_csv.py". Should be done via concat

**Comment by SteffenMeinecke** [comment]
Hi @okraft97 
this should have been adapted for branch develop by commit https://github.com/e2nIEE/simbench/commit/7c11af7fc9469a2aa82fbf0022ca1494aeeebbee. i just had no time to build a new release yet. It remains to be seen when i will get around to it.

**Comment by SteffenMeinecke** [comment]
now it is also fixed for the master branch and pypi package
