### ISSUE TITLE
Value error when accessing the network via Simbench code  (get_simbench_net)

### ISSUE THREAD

**Issue by shan-rak** [e2nIEE/simbench#3]
sb_code1 = "1-MVLV-semiurb-all-0-no_sw"  
net = sb.get_simbench_net(sb_code1)

Error:
 raise ValueError(
ValueError: cannot set using a multi-index selection indexer with a different length than the value

**Comment by SteffenMeinecke** [comment]
Hey shan-rak,
your code is fine and works with my installation.
It is a pandas Error.
What pandas version do you have installed?
Where in the SimBench code does the error occur?

**Comment by shan-rak** [comment]
Dear SteffenMeinecke,

Thank you for the quick response.
I'm using the latest version of pandas and simbench Pandas  = 1.1.0, Simbench = 1.0.0

You are right the problem is with pandas latest version 1.1.0. If I downgrade the pandas to 1.0.3. Everything works fine

With pandas 1.1.0 --> Simbench  crashes at    **csv_pp_converter.py** file    -->  _convert_measurement(csv_data)
May be they might have updated some api with newer pandas
