### ISSUE TITLE
Unit conversion in simbench 1.4.0 update

### ISSUE THREAD

**Issue by abs-n** [e2nIEE/simbench#35]
Since the pandapower 2.0 update is processing All the loads in the Mw unit and the simbench Low voltage dataset is in Kw, I wanted to kindly ask if the unit conversion for load profiles is considered to be injected into Pandapower time series power flow.

If this issue exists I would appreciate to provide me with a solution for this purpose.

**Comment by SteffenMeinecke** [comment]
I do not share the concerns, but I cannot say more about this unless you shown a concrete number that is wrong in your opinion.
