### ISSUE TITLE
FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated

### ISSUE THREAD

**Issue by tlogemann** [e2nIEE/simbench#37]
Hello,

i want to share the following `FutureWarning` that is thrown in the following environment:
We use `simbench==1.4.0` together with `pandapower==2.13.1` and `pandas==2.1.4` in a `python3.10` environment (see: https://gitlab.com/arl2/palaestrai/-/jobs/5888432431). That arises the following warning:

```
/opt/conda/lib/python3.10/site-packages/simbench/converter/csv_pp_converter.py:849: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_data[output_name] = pd.concat([output_data[output_name], input_data[
  ```
See: https://gitlab.com/arl2/palaestrai/-/jobs/5888432445

Maybe consider that, when developing further.

Regards

**Comment by SteffenMeinecke** [comment]
thanks for raising this issue

**Comment by SteffenMeinecke** [comment]
should be fixed for develop branch with commit https://github.com/e2nIEE/simbench/pull/40/commits/7e6bb96aeb630e7db2cc42406a6e740a83f9237f
