### ISSUE TITLE
'pandapowerNet' instance has no attribute 'load_p'

### ISSUE THREAD

**Issue by HafizRiaz** [e2nIEE/simbench#38]
Hi there, thank you for providing an excellent platform to simulate grid. i am trying simple code to use constant controller fro load and generator but i am facing this issue. your positive response will highly appreciated. 

import simbench as sb
grid_code = "1-HV-urban--0-sw"
net = sb.get_simbench_net(grid_code)
profiles = sb.get_absolute_values(net, profiles_instead_of_study_cases = True)

load_p = profiles[("load","p_mw")]
load_q = profiles[("load","q_mvar")]
sgen_p = profiles[("sgen","p_mw")]

print (load_p)

import pandapower.timeseries as ts
from pandapower.control.controller.const_control import ConstControl
from pandapower.timeseries.data_sources.frame_data import DFData

ds = DFData(sgen_p)
ConstControl(net, "sgen", "p_mw", element_index=net.sgen.index, profile_name=sgen_p.columns, data_source = ds)

ds = DFData(load_p)
ConstControl(net, "load", "p_mw", element_index=net.load_p.index, profile_name=load_p.columns, data_source = ds)

ds = DFData(load_q)
ConstControl(net, "load", "q_mvar", element_index=net.load_q.index, profile_name=load_q.columns, data_source = ds)

ts.OutputWriter(net, output_path="./", output_file_type= ".json")
ts.run_timeseries(net)
![error1](https://github.com/e2nIEE/simbench/assets/135654447/655feafe-d39e-47fb-b5ee-185e909e8ebd)

**Comment by SteffenMeinecke** [comment]
Dear @HafizRiaz, 
you need to change the last two ConstControl definitions as follows

ds = DFData(load_p)
ConstControl(net, "load", "p_mw", element_index=**net.load.index**, profile_name=load_p.columns, data_source = ds)

ds = DFData(load_q)
ConstControl(net, "load", "q_mvar", element_index=**net.load.index**, profile_name=load_q.columns, data_source = ds)

**Comment by HafizRiaz** [comment]
Thanks you so much for your kind and quick response. Have a good day and stay blessed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
