### ISSUE TITLE
List of grid codes

### ISSUE THREAD

**Issue by viktor-ktorvi** [e2nIEE/simbench#41]
Hi,

I'd like to search through all the simbench grids in a for loop to find some I like based on some criteria. To do that, I manually have to copy all grid codes. Is there a file or list or something, where all the existing grid codes are available and can be easily copied or loaded into python?

**Comment by TheBigFudge** [comment]
You can use the collect_all_simbench_codes() Funktion without any parameters for that. With this you get a list of all sb codes:


```python
all_codes = sb.collect_all_simbench_codes()
print(all_codes)
```

**Comment by SteffenMeinecke** [comment]
@viktor-ktorvi you can find introductions to the function in the [tutorial](https://github.com/e2nIEE/simbench/blob/develop/tutorials/simbench_grids_basics_and_usage.ipynb). Furthermore, I just added the function `collect_all_simbench_codes()` to the documentation (on develop).
