### ISSUE TITLE
net.loadcases

### ISSUE THREAD

**Issue by hitchenzhe** [e2nIEE/simbench#9]
Hello,

I am using simbench as a test model. I do not know what does the net.loadcases mean?
net.loadcases
Out[207]: 
            pload     qload  Wind_p  PV_p  RES_p  Slack_vm
Study Case                                                
hL            1.0  1.000000    0.00  0.00    0.0     0.965
n1            1.0  1.000000    0.00  0.00    0.0     0.965
hW            1.0  1.000000    1.00  0.80    1.0     0.965
hPV           1.0  1.000000    0.85  0.95    1.0     0.965
lW            0.1  0.122543    1.00  0.80    1.0     1.055
lPV           0.1  0.122543    0.85  0.95    1.0     1.055

If I want remove all the default wind, PV, sgen generation, how can we make it? set value to 0?

Best,

**Comment by SteffenMeinecke** [comment]
Do you want to set all active power of static generator to zero? `net.sgen["p_mw"] = 0`

Do you want to remove all static generators? -> use the pandapower functionality `pp.drop_elements_simple(net, "sgen", net.sgen.index)`

Do you want to use the predefined studycases in net.loadcases? -> please, have a look at the jupyter notebook https://github.com/e2nIEE/simbench/blob/master/tutorials/simbench_grids_basics_and_usage.ipynb

Detailed information on the topic of "predefined studycases" can be found in several publications at https://simbench.de/en/download/publications/ e.g.:

- documentation - chapter 5.1 Defined SimBench study cases)
- paper "GENERAL PLANNING AND OPERATIONAL PRINCIPLES IN GERMAN DISTRIBUTION SYSTEMS USED FOR SIMBENCH" (section DEFINITION OF RELEVANT DIMENSIONING CASES)
